Repository Team-Miaam/RudimentaryMiaam, pull requests merged in 2021-10, with the labels that each got.

#36 documentation of constructor of scene
  src/core/scene.js
Labels: documentation

#37 update
  .gitignore
  src/core/scene.js
Labels: documentation

#41 ahhh...
  src/core/scene.js
Labels: bug, documentation

#48 animation with texture rotations
  index.js
  src/core/animation.js
Labels: enhancement, r&d

#51 #50 advanced animation primary stage complete
  src/core/animation.js
  src/util/common.js
Labels: enhancement, r&d
